### ISSUE TITLE
Add tests and badges like GitHub Actions CI, code coverage, Maven link, etc

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/jcasbin-mongo-adapter#2]

**Comment by hsluoyz** [comment]
@shy1st

**Comment by shy1st** [comment]
@hsluoyz @zzl221000 Sorry, owing to the fact that I have no authority of this project.，I can not configure the codecov of this project.

**Comment by zzl221000** [comment]
@shy1st  I have invited you as a collaborator, do you have permission to operate?

**Comment by hsluoyz** [comment]
@zzl221000 can you invite @shy1st and me as the "admin" of this project?

**Comment by zzl221000** [comment]
@hsluoyz Personal repositories can only add collaborators, there is no option for roles.

**Comment by shy1st** [comment]
@zzl221000  I can not still add new repository in the codecov. You also can add new repository in the codecov and configure the secret key of the codecov of this project as the repository secret. If you finished the configuration, please tell me the secret name(not secret content.

**Comment by zzl221000** [comment]
@shy1st name is `CODECOV_TOKEN`. 
Github tells me that an invitation email was sent to you. It is waiting for you to join.
