### ISSUE TITLE
Proposal to Transfer jcasbin-mongo-adapter project to jcasbin

### ISSUE THREAD

**Issue by zzl221000** [jcasbin/jcasbin-mongo-adapter#5]
Hello @hsluoyz :
 I am reaching out to discuss the future of the jcasbin-mongo-adapter project, which I have been maintaining. As you may know, this adapter provides a MongoDB storage backend for jcasbin.

Over the past period, my focus and professional commitments have shifted away from Java development, which has led to a decrease in my ability to dedicate sufficient time and resources to maintain and improve the jcasbin-mongo-adapter. This change in my professional landscape has made it challenging for me to continue providing the level of support and updates that the project and its users deserve.

Given the jcasbin's expertise and active involvement in the development and maintenance of Casbin-related projects, I believe that transferring the jcasbin-mongo-adapter to jcasbin would be in the best interest of the project and its community. This transfer would ensure that the adapter continues to evolve, receive necessary updates, and maintain compatibility with the latest versions of jcasbin.

I am open to discussing the terms and conditions of this transfer, including any necessary steps to ensure a smooth transition. I am also willing to assist in any way possible to ensure that the transfer process is as seamless as it can be for the community and the project's users.

Please let me know if you are interested in taking on the jcasbin-mongo-adapter project and how we might proceed with this transfer. I am confident that under the jcasbin organization's stewardship, the project will continue to thrive and meet the needs of its users.

Thank you for considering this proposal. I look forward to your thoughts and any questions you may have.

Best regards,

**Comment by hsluoyz** [comment]
@zzl221000 plz join the QQ group for discussion: 546057381
